version: '2'
services:
  proxy:
    image: monitoringartist/play.monitoringartist.com
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
    links:
     - zabbix:zabbix
  zabbix-db:
    image: monitoringartist/zabbix-db-mariadb
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_USER=zabbix
      - MARIADB_PASS=my_password
  zabbix:
    image: monitoringartist/zabbix-xxl:latest
    depends_on:
      - zabbix-db
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - zabbix-db:zabbix.db
    environment:
      - ZS_DBHost=zabbix.db
      - ZS_DBUser=zabbix
      - ZS_DBPassword=my_password
