version: '2'
services:
  play-proxy:
    image: monitoringartist/play-proxy:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
    links:
     - play-zabbix:play-zabbix
     - play-grafana:play-grafana
     - play-vector:play-vector
     - play-cadvisor:play-cadvisor
     - play-elasticsearch:play-elasticsearch
     - play-kibana:play-kibana
     - play-prometheus:play-prometheus
    depends_on:
     - play-zabbix
     - play-grafana
     - play-vector
     - play-cadvisor
     - play-elasticsearch
     - play-kibana
     - play-prometheus
  play-zabbix-db:
    image: monitoringartist/zabbix-db-mariadb:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_USER=zabbix
      - MARIADB_PASS=my_password
  play-zabbix:
    image: monitoringartist/zabbix-xxl:latest
    depends_on:
      - play-zabbix-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - play-zabbix-db:zabbix.db
    environment:
      - ZS_DBHost=zabbix.db
      - ZS_DBUser=zabbix
      - ZS_DBPassword=my_password
      - XXL_zapix=true
      - XXL_grapher=true
  play-zabbix-agent:
    image: monitoringartist/zabbix-agent-xxl-limited:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /:/rootfs
      - /var/run:/var/run
    ports:
      - 10050:10050
  play-grafana:
    image: monitoringartist/grafana-xxl:latest
    depends_on:
      - play-grafana-data
    volumes:
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - play-grafana-data
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:/grafana/
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    ports:
      - 3000:3000
  play-grafana-data:
    image: monitoringartist/play-grafana-data:latest
  play-vector:
    image: netflixoss/vector:latest
  play-cadvisor:
    image: google/cadvisor:latest
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - /etc/localtime:/etc/localtime:ro
  play-elasticsearch:
    image: elasticsearch:latest
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    command: -E transport.host=localhost
  play-kibana-config:
    image: monitoringartist/play-kibana-config:latest
  play-kibana:
    image: kibana:latest
    depends_on:
      - play-kibana-config
    volumes:
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - play-kibana-config
    ports:
      - 5601:5601
    depends_on:
      - play-elasticsearch
    environment:
      ELASTICSEARCH_URL: http://play-elasticsearch:9200
      NODE_OPTIONS: "--max-old-space-size=600"
    links:
      - play-elasticsearch:play-elasticsearch
    command: --config /etc/kibana/kibana.yml
  play-logstash-config:
    image: monitoringartist/play-logstash-config:latest
  play-logstash:
    image: logstash:latest
    ports:
      - 5000:5000
    depends_on:
      - play-elasticsearch
      - play-logstash-config
    volumes:
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - play-logstash-config
    links:
      - play-elasticsearch:play-elasticsearch
    entrypoint: logstash -f /etc/logstash/conf.d/logstash.conf
  play-logspout:
    image: bekt/logspout-logstash
    restart: on-failure
    environment:
      ROUTE_URIS: logstash+tcp://play-logstash:5000
      LOGSTASH_TAGS: docker,playground
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - play-logstash
    links:
      - play-logstash:play-logstash
  play-prometheus-config:
    image: monitoringartist/play-prometheus-config:latest
  play-prometheus:
    image: prom/prometheus:latest
    depends_on:
      - play-cadvisor
      - play-prometheus-config
    volumes:
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - play-prometheus-config
    links:
      - play-cadvisor:play-cadvisor
      - play-node-exporter:play-node-exporter
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-web.route-prefix=prometheus'
  play-node-exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
